### ISSUE TITLE
100% cpu utilisation when no controller connected

### ISSUE THREAD

**Issue by terencode** [joaorb64/joycond-cemuhook#5]
![image](https://user-images.githubusercontent.com/12665563/80867796-4642fe00-8c96-11ea-9e04-b0244374be1c.png)

**Comment by joaorb64** [comment]
Damn! Will investigate. Didn't really test a lot with no controllers connected.

**Comment by joaorb64** [comment]
Does this happen when you just run the program? Or did you connect a controller and then disconnected it to get 100% CPU usage?
Here if I just run the program I get 25% CPU which is already bad to be honest.

**Comment by terencode** [comment]
Yep, I get 100% cpu usage right when starting the program and also after disconnecting my Pro controller.

**Comment by joaorb64** [comment]
Can you check if 455672407c744c180c3112c90864974f8d2f420d solves it?
Here I get 0% CPU usage without controllers, and if I connect a Pro controller it goes up to 9%.

**Comment by terencode** [comment]
Yes, it works, thanks!
Why set sleep to 0.2 and not something else by the way?

**Comment by joaorb64** [comment]
Mostly based on this post: https://stackoverflow.com/a/10926766 and because in other solutions I found people either linked to this one or just used 0.2 without an explanation. In therms of the program's performance, I think this won't make a real difference in response time, as it's only for the thread that checks for new or disconnected controllers.

**Comment by terencode** [comment]
Ok yes thanks, I'm going to submit a PR for a systemd .service file now :)
