### ISSUE TITLE
Cemu 19.0 d-pad on Switch Pro Controller not able to map.

### ISSUE THREAD

**Issue by bernharl** [joaorb64/joycond-cemuhook#8]
I installed Cemu 19.0 via Lutris. Cemu detects the DSUclient and is able to map all buttons except for the d-pad, home-button and screenshot button.

The controller is confirmed to work 100% with Citra (which is Linux native), motion controls and everything. 

I am running Manjaro Linux.

**Comment by joaorb64** [comment]
Which device are you using when mapping the controller? The DSU one, dinput or xinput?
Also, because the PS4 controller only has options, share and home (ps) one of +, -, home, screenshot will always be out. What you can do though is configure to use motion from joycond-cemuhook but input from the dinput/xinput device.

**Comment by bernharl** [comment]
I'm using the DSUserver as input. I'm not sure if cemu 19.0 changed something because I could not find any way to get motion from DSU while using dinput for other inputs. Obviously that is an issue for Cemu and not for this project if so though.

**Comment by bernharl** [comment]
Ok, I got it to work by installing Cemuhook which seemingly is the only way to get motion input from DSU while using another API for button inputs. I thought Cemuhook was obsolete, but apparently not. Thank you!

**Comment by 190n** [comment]
@bernharl Would you mind describing exactly how you got it working? I'm having the same issue on Cemu 1.20 even with Cemuhook installed, but my input settings may be different or something.

**Comment by bernharl** [comment]
Use DirectInput as the controller API in input settings. Configure "gamepad motion source" separately. Keep in mind that I haven't tested this on cemu 1.20 and I cannot test it right now as I am at work. Tell me if it works.

**Comment by joaorb64** [comment]
I'm testing it right now using a Pro Controller.
I have Cemu 1.20 installed via Lutris, using the latest cemuhook (Cemuhook 0.5.7.3 for 1.12.1-1.19.3).
I went on Options>Input Settings, disabled all inputs. Then Options>Gamepad motion source>(checked both "DSU1 (by slot)" and "Also use for buttons/axes".
Everything is working aside from dpad, which is weird considering Dolphin reads the dpad.

Alternatively, you can go on Options>Input Settings and set a Wii U Gamepad using either DSU Client (client 1) or DirectInput (Nintendo Switch Pro Controller (event)) if you want to change the input mappings.

**Comment by joaorb64** [comment]
Turns out the dpad issue was a bug. We end up with one less bug in the project and a few less Bokoblins in Hyrule :P

**Comment by 190n** [comment]
Fantastic! Thanks for fixing this so quickly!

The AUR package is borked:

```
==> ERROR: Integrity checks (sha512) differ in size from the source array.
```

I think you need to add a SHA512 sum for `run.sh` as that file is new. But the D-Pad works now!

**Comment by bernharl** [comment]
Oh, I will fix the AUR package, sorry about that.

**Comment by Toastee480** [comment]
Sorry to bring back such an old issue, but this is happening to me again on Cemu 1.22.6. I have Cemuhook installed, and the D-Pad partially works, but there's no input from the up or left D-Pad inputs. I'm also having issues using this with dolphin, with the server not being listed as a device at all. I'm on arch linux, though I've tried cloning the repo rather than using the AUR package and the same issue happens.
